### ISSUE TITLE
PCP-23-2: Build blob file using zstd dictionary compression

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/titan#118]
This is subtask of https://github.com/tikv/tikv/issues/5743

Add `CompressionOptions blob_file_compression_options` to `TitanCFOptions`. `BlobFileBuilder` should respect `blob_file_compression_options.enabled`. Also if `max_dict_bytes > 0`, encode the content using zstd dictionary. If `zstd_max_train_bytes = 0`, it should use all the content as samples to train dictionary; otherwise, the first `zstd_max_train_bytes` is used. The samples should be store in memory before the dictionary is trained, and then flush to file after that. The dictionary will be stored in blob file as meta block.

For now, update `BlobFileReader` and `BlobFileIterator` to return `Status::NotSupported` if they encounter a file come with dictionary compression. We will update them in the next task.

Update table_builder_test to add tests for the change.

**Comment by yiwu-arbug** [comment]
@foeb

**Comment by chux0519** [comment]
Hi, I'm looking into this issue recently, and have following questions about the blob file format:

1. A none zero `flag(Fixed32)` in `BlobFileHeader` section indicates this is a compressed blob file by now, is this right ?
2. There is no room for dictionary in `BlobFileMeta` section, should I add a new field sperately ? like 

```
+-------------+-----------+--------------+------------+
| file number | file size | file entries | file level |
+-------------+-----------+--------------+------------+
|  Varint64   | Varint64  |   Varint64   |  Varint32  |
+-------------+-----------+--------------+------------+
+--------------------+--------------------+
|    smallest key    |    largest key     |
+--------------------+--------------------+
| Varint32 + key_len | Varint32 + key_len |
+--------------------+--------------------+
+---------------------------+
|         dictionary        |
+---------------------------+
| Varint64 + dictionary_len |
+---------------------------+
```

Does this looks OK?
