### ISSUE TITLE
live-blob-size is much larger than total size of blob file

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/titan#119]
![image](https://user-images.githubusercontent.com/16376959/69535677-64098a00-0fb7-11ea-92b5-a4f19bf8834a.png)

Value of metric `live-blob-size` is much larger than total size of blob file, and when most of data has been removed, it is still so larger (ten times than its actual size).

The reason is `Titan` would add `live-blob-size` by the length of raw value every time it adds a new key into Blob file.  , rather than encoded value. And it collects size of encoded value in `BlobFileSizeCollector`. When Titan deleted files, it would subtract `live-blob-size` by size stored in `BlobFileSizeCollector`. So the value it subtracted is always less than the value it added.

**Comment by caipengbo** [comment]
How is the issue going？

**Comment by Connor1996** [comment]
No progress. You can take a look. I guess it's due to the encoded value is in compression.
