### ISSUE TITLE
Using BOTTOM priority threadpool to schedule GC will influence bottom level compaction

### ISSUE THREAD

**Issue by wujy-cs** [tikv/titan#124]
Currently we use BOTTOM priority threadpool to schedule gc, but rocksdb will schedule bottom level compaction with BOTTOM priority too if that threadpool is not empty. So 
1. If we set low max_background_gc  but high max_background_jobs, data will be prevented from compacting to last level especially if we enabled level merge.
2. There will be resource competition between gc thread and compaction thread.

**Comment by wujy-cs** [comment]
@yiwu-arbug @Connor1996

**Comment by yiwu-arbug** [comment]
Interesting finding. I misunderstood what bottom-pri mean. I thought it's kind of a lowest-pri threadpool where bottommost level will use the normal low-pri pool if the bottom-pri pool is fully utilized.

**Comment by Connor1996** [comment]
@yiwu-arbug How about using `Priority::USER` instead for Titan GC?

**Comment by Connor1996** [comment]
Seems we can leverage the bottom-pri pool to reduce the write stall possibility when level-merge/range-merge enabled. See https://github.com/facebook/rocksdb/pull/3835

Also, I'm curious how you find this problem. As expected, we will disable Titan background GC when level-merge enabled.

**Comment by wujy-cs** [comment]
> Also, I'm curious how you find this problem. As expected, we will disable Titan background GC when level-merge enabled.

Because I found max_background_gc will influence space amplification significanttly (very!) even if BackgroundGCCall is bypassed while level_merge is enabled, same as actual size ratio among LSM-Tree levels.

**Comment by wujy-cs** [comment]
> @yiwu-arbug How about using `Priority::USER` instead for Titan GC?

I have tried, I think it's ok.

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug How about using `Priority::USER` instead for Titan GC?

Let's do that for now.

**Comment by Connor1996** [comment]
> Because I found max_background_gc will influence space amplification significantly (very!) even if BackgroundGCCall is bypassed by level_merge, same as actual size ratio among LSM-Tree levels.

Wait a minute. When Titan background GC is disabled, the BOTTOM is not set no matter how `max_background_gc. why it will influence still?

**Comment by wujy-cs** [comment]
> > Because I found max_background_gc will influence space amplification significantly (very!) even if BackgroundGCCall is bypassed by level_merge, same as actual size ratio among LSM-Tree levels.
> 
> Wait a minute. When Titan background GC is disabled, the BOTTOM is not set no matter what's the value of `max_background_gc`. why it will influence still?

we did not disable GC, just bypassed MaybeScheduleGC() call after compactoin.

**Comment by Connor1996** [comment]
oh, so you didn't set `disable_background_gc` explicitly. got it.
