### ISSUE TITLE
Implement PrioritizedCache

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/titan#127]
Implement `PrioritizedCache`, which wraps a single `LRUCache`, but have additional API to return child `Cache` instances that:
* HighPriCache: always insert into the cache with high-priority, regardless of user provided option
* LowPriCache: always insert into the cache with low-priority, regardless of user provided option

Part of https://github.com/tikv/tikv/issues/5742

**Comment by yiwu-arbug** [comment]
cc @haoxiang47

**Comment by haoxiang47** [comment]
Hi @yiwu-arbug , sorry for late for this PCP, I had simplily add a PR: https://github.com/tikv/rocksdb/pull/144 for this issue, add HighPriCache and LowPriCache two interface in rocksdb

**Comment by yiwu-arbug** [comment]
> Hi @yiwu-arbug , sorry for late for this PCP, I had simplily add a PR: [tikv/rocksdb#144](https://github.com/tikv/rocksdb/pull/144) for this issue, add HighPriCache and LowPriCache two interface in rocksdb

Thank much for the work! Commented on the PR.

**Comment by Connor1996** [comment]
As blob specific cache priority is introduced, close it https://github.com/tikv/rocksdb/pull/354
