### ISSUE TITLE
error when include titan library in my project

### ISSUE THREAD

**Issue by linuxpham** [tikv/titan#143]
when I add "titan.h",  I saw the below issue : 
**

> /usr/include/titan/options.h:6:10: fatal error: logging/logging.h: No such file or directory

**
Where is the location of "logging/logging.h" ?
Thanks!

**Comment by Connor1996** [comment]
Titan adds rocksdb dir into search path when building, `logging/logging.h` is in rocksdb

**Comment by yiwu-arbug** [comment]
Looks like your rocksdb version is stale. Please refer to titan/README for the right version.

**Comment by linuxpham** [comment]
I can not see "logging" folder in my "rocksdb" folder :

![Screen Shot 2020-02-25 at 20 23 19](https://user-images.githubusercontent.com/154762/75251212-bb183880-580c-11ea-932d-e42a200fe2f3.png)
 
is there any way to build titan with facebook rocksdb v6.6.4 (dynamic link) ?

**Comment by linuxpham** [comment]
I can not see any rocksdb folder in "titan" folder :

![Screen Shot 2020-02-25 at 20 27 02](https://user-images.githubusercontent.com/154762/75251511-501b3180-580d-11ea-96b8-009515d87f12.png)

do I need to copy "tidb rocksdb" to "titan" folder?

**Comment by yiwu-arbug** [comment]
The file is under rocksdb root directory, not the header directory include/rocksdb: https://github.com/facebook/rocksdb/tree/6.6.fb/logging

Yes you can dynamic link with rocksdb, but you still need to checkout rocksdb source code and specify `ROCKSDB_DIR` to build libtitan.a.

**Comment by yiwu-arbug** [comment]
btw Titan is not compatible with rocksdb 6.6.4 so far. We currently support rocksdb 6.4.x.

**Comment by linuxpham** [comment]
Thank so much!
