### ISSUE TITLE
GC is not triggered as expected

### ISSUE THREAD

**Issue by liumh8** [tikv/titan#144]
https://github.com/tikv/titan/blob/4dc4ba89f8999c2981cf916badb088f86b4db227/src/blob_gc_picker.cc#L47
https://github.com/tikv/titan/blob/4dc4ba89f8999c2981cf916badb088f86b4db227/src/blob_gc_picker.cc#L69
In some cases, "estimate_output_size" is larger than "cf_options_.blob_file_target_size" , but "batch_size" is less than "cf_options_.max_gc_batch_size", then BasicBlobGCPicker will return nullptr, but there are many blob files whose "gc_score" is larger than "cf_options_.blob_file_discardable_ratio" and need to be gc in fact. In one of my tests, Titan use disk 190GB after writing some random data, then I remove the condition "estimate_output_size >= cf_options_.blob_file_target_size" and in the same test, Titan use disk 170GB.

**Comment by yiwu-arbug** [comment]
@liumh8 Great finding! Do you mind send a fix?
