### ISSUE TITLE
how to set the blob_file_compression modle 

### ISSUE THREAD

**Issue by niyaozhushuma** [tikv/titan#153]
I am a freshman in titan!
I want test different compression strategy，I change  the option,h file  
 from CompressionType blob_file_compression{kNoCompression} 
 to CompressionType blob_file_compression{kLZ4Compression}  but it don't work,
how can I do it? Thanks for your help

**Comment by Connor1996** [comment]
already answered in private. It's due to `lz4` is not linked.
