### ISSUE TITLE
After enabling titan, whether the value obtained in the compaction filter is BlobIndex

### ISSUE THREAD

**Issue by gotoxu** [tikv/titan#162]
我们在TiKV中定制了一个Compaction Filter，逻辑是根据保存的value中的内容做一些过滤。假如现在我改用titan引擎，那么我在`Filter` API中拿到的value是否就变成`BlobIndex`了？

如果的确如此，那么：

1. 如何判断value是真实值还是`BlobIndex`
2. 如果是`BlobIndex`，那么如何通过`BlobIndex`获取`BlobRecord`

**Comment by Connor1996** [comment]
You can check this https://github.com/tikv/titan/blob/master/src/db_impl.cc#L596

**Comment by gotoxu** [comment]
感谢您的回复！

我看了你们提供的代码片段，`titan`的`Get`实现用到了：

1. 通过`DBImpl->GetImpl`接口获取value，并同时判断value是否为`BlobIndex`
2. 如果是，那么通过`BlobFileSet->GetBlobStorage`获取`BlobStorage`，再通过`BlobStorage->Get`获取真实的值

问题是，在`CompactionFilter`中我如何基于`TitanDB`获取`BlobStorage`对象，`TitanDB`能否考虑增加一个公共接口访问`BlobFileSet`对象，或者直接根据`cf_id`访问`BlobStorage`对象。

另外，`rust-rocksdb`项目中会不会考虑增加对`BlobStorage`对象的支持？

**Comment by yiwu-arbug** [comment]
@gotoxu currently Titan doesn't support compaction filter, since it is not returning the user value to the compaction filter. Supporting it is however not very difficult. I filed #163 to track. Are you interest in contribute? If so I can fill in more details in that issue.

**Comment by gotoxu** [comment]
Look #163
