### ISSUE TITLE
Titan should return user value to compaction filter

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/titan#163]
Currently when user using compaction filter, the compaction filter is pass to underlying rocksdb as-is. As a result, the value returned is the blob index rather than the user value. Titan should wrap around the user compaction filter to return user value to the compaction filter. Also it needs to allow user compaction filter co-exists with the compaction filter used by Titan itself when `gc_merge_rewrite=true`.

**Comment by yiwu-arbug** [comment]
This is required by compaction filter GC of TiKV.

**Comment by gotoxu** [comment]
我认为可以有两种实现方式：

1. 可以为`titan`重新实现一个`TitanCompactionFilter`，继承自`CompactionFilter`，并重写`FilterV2`方法。当`value_type == kBlobIndex`时，从`BlobStorage`中取得真实的值并调用`Filter`方法。这样实现改动应该最小，但是由于每次都需要从`BlobStorage`中Get真实的值，因此Compaction的性能会有所下降。

2. 或者我们可以将TTL值直接编码到`BlobIndex`中。在`CompactionFilter`中直接判断`BlobIndex`是否过期，过期则淘汰。但是这样做需要给`TitanDB`添加新的Put接口（例如: `PutWithTTL`）传入TTL值。另外还需要修改BlobIndex的编码方式。

这两种方案仅是我个人意见，供你们参考。

**Comment by Connor1996** [comment]
So your requirement is to support TTL?  I prefer the second way.

**Comment by gotoxu** [comment]
@Connor1996 rocksdb的TTL是基于DB的，我想大多数用户的需求应该是要基于key的。所以我们需要提供一个独立的PutWithTTL接口来实现，并重新设计BlobIndex的编码方式。

**Comment by yiwu-arbug** [comment]
可能需要针对实际场景做一些测试，不确定方案1对性能影响有多大。我觉得只要相比原生 rocksdb 性能要好就可以接受（compaction的 IO 读带宽占用可能没有减少，但是写带宽占用减少了；cpu占用比较难分析，但估计也是减少的）。另外方案1可能可以提供一个选项就是是否需要用户value。

**Comment by gotoxu** [comment]
@yiwu-arbug 我来编写这部分代码吧，新建一个TitanCompactionFilter，重新实现FilterV2方法。

关于在CompactionFilterFactory中创建TitanCompactionFilter时获取到当前TitanDB实例有没有什么好的建议？

**Comment by yiwu-arbug** [comment]
@gotoxu 多谢。在TitanDBImpl::Open里面检查一下DBOptions里面有没有设置compaction-filter，有就换成TitanCompactionFilter。这个时候就可以获取TitanDBImpl实例了。

**Comment by gotoxu** [comment]
@yiwu-arbug please review [PR](#164 )

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug please review [PR](https://github.com/tikv/titan/pull/164)
> 
> `CreateColumnFamily`接口还未修改，先评审一下这种方案是否可行。如果可以再继续修改!

多谢，我明天再仔细看看。
