### ISSUE TITLE
performance enhancements on RaftMsgCollector

### ISSUE THREAD

**Issue by zhuboshuai** [tikv/titan#184]
3 machines :
CPU: 2 x Intel Xeon Gold 5118 @ 2.30GHz, 24 Cores 48 Threads in total  
Memory: 196GB  
SSD: 8 x INTEL SSDSC2KB96 (960GB)
topology:
one pd-server and on tikv-server on every machine, no tidb-servers
workload:
there are 500M keys, the values of key are from 1 to 500M. all the values are 1k size. 100K QPS to read.
titan engine is used.
profile: 
![collect-0](https://user-images.githubusercontent.com/10694566/91721576-9477f780-ebcb-11ea-96f8-b147d3859e75.png)
![collect](https://user-images.githubusercontent.com/10694566/91721605-9e99f600-ebcb-11ea-8e58-aaa1ab031e98.png)
from the flamegraph the 'Collect' method‘s width is far larger then 'rallocx' mothed which is revoked by  itself.
i think it corresponds 'BatchCollector<Vec<RaftMessage>, RaftMessage> for RaftMsgCollector'.
so is precomputing the RaftMessage's size a good idea?

**Comment by Connor1996** [comment]
It's unrelated with Titan, please create the issue in tikv repo.
