### ISSUE TITLE
Does titan support backup/checkpoint like rocksdb

### ISSUE THREAD

**Issue by ShooterIT** [tikv/titan#205]
Hi, thanks to high performance of titan in big value scenario, compared with rocksdb.  So I want to support titan as key value storage engine in our project [Kvrocks](https://github.com/bitleak/kvrocks).  But I find some problems in using titan. 

I use `rocksdb::BackupEngineImpl::CreateNewBackupWithMetadata` to create a backup when using titan, but i find `titan` directory that includes `blob` files doesn't be copied to backup directory, maybe I miss something,  I should use other interfaces to do that. Moreover, does titan support checkpoint that can hard link blob files in titan directory?

**Comment by Connor1996** [comment]
Titan doesn't support the backup/checkpoint of RocksDB. So, of course, `titan` directory is not included when you call rocksdb's API `CreateNewBackupWithMetadata`.

**Comment by ShooterIT** [comment]
@Connor1996 Thanks for your quick reply. I know little about tikv, I have a question, how does tikv create data snapshot and send when full replication synchronization if tikv uses titan engine?
Otherwise, do you have plan to implement backup/checkpoint for titan?

**Comment by Connor1996** [comment]
TiKV just scans out the range of data and generates an SST file and sends the file to the target replica. There is no difference when using Titan.

We have no plan for it. But you can send a PR to support it.

**Comment by ShooterIT** [comment]
@Connor1996 Thanks very much, we will have a look.

**Comment by yiwu-arbug** [comment]
@ShooterIT for discussion about Titan you can join tikv-wg.slack.com and then join #sig-engine channel. I'm closing the issue.

**Comment by caipengbo** [comment]
I want to support this feature, but I hit a problem, can @yiwu-arbug invite me to join tikv-wg.slack.com?

**Comment by caipengbo** [comment]
Hi @ShooterIT, I added checkpoint support to Titan and created  #207, hope it will be helpful to your project :)
