### ISSUE TITLE
[feature request] BlobFileSet support MVCC mechanism

### ISSUE THREAD

**Issue by caipengbo** [tikv/titan#206]
At present, titan manage BLOB files through `BlobFileSet` class. `BlobFileSet` does not implement MVCC mechanism, titan need to hold mutex for the change of blob version. 

Do we plan to implement MVCC mechanism similar to Rocksdb `Version` in the future?

**Comment by Connor1996** [comment]
No plan. Titan actually has blob file MVCC mechanism similar to `Version` before. But we remove it to reduce lock.

**Comment by caipengbo** [comment]
I think the MVCC mechanism can reduce lock, why do you say that the MVCC mechanism increases lock?

**Comment by Connor1996** [comment]
See https://github.com/tikv/rocksdb/pull/83/files#diff-7178b6d26df96cb0d0491e3ce4ab181146542108375855327c59f5875cb25818L449, it needs a lock every time getting a snapshot. But not every get will get a large value from Titan.
