### ISSUE TITLE
[Feature Request] Support more iterators about BLOB files

### ISSUE THREAD

**Issue by caipengbo** [tikv/titan#208]
I found that Titan has very few types of iterators for BLOB files, and only two types of iterators(`BlobFileIterator` `BlobFileMergeIterator`) are used for BLOB GC. 

More abundant iterators can achieve more RocksDB compatible interfaces, such as `GetApproximateSizes` and so on, Which could lead to more people choosing Titan.

Does Titan plan to implement more iterators for the BLOB files in the future?

**Comment by Connor1996** [comment]
we don't have the plan
