### ISSUE TITLE
Many Get() is missing after fillrandom

### ISSUE THREAD

**Issue by HBKO** [tikv/titan#215]
I use titandb_bench to test fillrandom,readrandom，But many reads are missing.

All installations of titan are default, The version of RocksDB is v6.4.

titandb_bench command is:
numactl -N 1 ../build/titandb_bench --db=/home/hkw/RocksDB_Data/ --wal_dir=/pmem6/hkw/ --value_size=1024 --benchmarks=fillrandom,readrandom --num=1048576 --compression_type=none --disable_wal=false --inplace_update_support=false --reads=100000

The result is:
DB path: [/home/hkw/RocksDB_Data/]
Write Operation Start
fillrandom   :      28.038 micros/op 35666 ops/sec;   35.4 MB/s
DB path: [/home/hkw/RocksDB_Data/]
readrandom   :    1037.437 micros/op 963 ops/sec;    0.6 MB/s (63069 of 100000 found)

But I use the same command on RocksDB. The Get() is all hit.
 db_bench command is:
numactl -N 1 ../build/db_bench --db=/home/hkw/RocksDB_Data/ --wal_dir=/pmem6/hkw/ --value_size=1024 --benchmarks=fillrandom,readrandom --num=1048576 --compression_type=none --disable_wal=false --inplace_update_support=false --reads=100000
DB path: [/home/hkw/RocksDB_Data/]
Start write tid:21575
fillrandom   :      42.021 micros/op 23797 ops/sec;   23.6 MB/s
DB path: [/home/hkw/RocksDB_Data/]
readrandom   :     361.050 micros/op 2769 ops/sec;    2.7 MB/s (100000 of 100000 found)

Additional:
The readrandom after fillseq in titandb_bench，All Get() is hit.

**Comment by Connor1996** [comment]
Not quite familiar with how the randrandom performs. Do you have any idea? @yiwu-arbug

**Comment by yiwu-arbug** [comment]
I believe with fill random, keys are randomly generated and not necessary cover the full key range, so a subsequent read random can get misses. I'm not sure why with rocksdb there's all hits. Maybe there are changes to db_bench in upstream that is not merged into our branch. What's the rocksdb version you use?

**Comment by HBKO** [comment]
Thanks for your reply.
The version of rocksdb I use is v6.4. I agree with your view that reading after random writing does not have to hit all. But the missing key is too much. I fillrandom 1M Key. But hit rate is about 60% after search 100K Key-Value. 
But this problem is not big deal.

**Comment by yiwu-arbug** [comment]
I think the command you use is doing 1M key fillrandom into a 1M key range, since you only specify `--num`.
