### ISSUE TITLE
Support for C bindings

### ISSUE THREAD

**Issue by gotoxu** [tikv/titan#217]
Can we provide C bindings for titan db? 

Just like [rocksdb/c.h](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/c.h) and [rocksdb/c.cc](https://github.com/facebook/rocksdb/blob/master/db/c.cc)

**Comment by yiwu-arbug** [comment]
You can extract them from https://github.com/tikv/rust-rocksdb/tree/master/librocksdb_sys/crocksdb
