### ISSUE TITLE
Add tags to GitHub repo for ease of search

### ISSUE THREAD

**Issue by karuppiah7890** [tikv/titan#224]
Some tags like `database` and similar in the GitHub repo would help with the repo's search-ability when looking at topics like database - https://github.com/topics/database or searching on GitHub https://github.com/search , https://github.com/search/advanced

**Comment by Connor1996** [comment]
Thanks for your advice. Add tags `database` and `rocksdb`

**Comment by karuppiah7890** [comment]
Thanks @Connor1996 !
