### ISSUE TITLE
Misunderstand why titan need create snapshot on Get/MultiGet/NewIterator

### ISSUE THREAD

**Issue by BaronStack** [tikv/titan#225]
I'm confused why titan's Get or some other read operations need to create a snapshot.

To protect the consistency between Get lsm-tree and blobfile?

- For lsm-tree: we have superversion to keep the current key  is always exists and the index value from lsm-tree is pinable.
- For blobfile: GC's schedule  is after compaction  and need a long time to finish. The index value's blob file can't be deleted when BlobStorage::Get.

**Comment by Connor1996** [comment]
It's not necessary now. Actually, it's necessary for the previous design which combines the superversion with blob version. But we didn't remove this when changing the code, as we can do something on the hook `ReleaseSnapshot`. Anyway, if it doesn't provide a snapshot, RocksDB would create a snapshot innerly. So not much difference here.
