### ISSUE TITLE
Have you compared the performance of titan and BlobDB? 

### ISSUE THREAD

**Issue by gotoxu** [tikv/titan#228]
It seems that [BlobDB's](https://github.com/facebook/rocksdb/wiki/BlobDB) GC strategy is more concise and efficient. Have you tested the performance difference between them? 

In addition, the rocksdb currently used by TiKV is version 6.4. Do you have any plans to upgrade rocksdb version?

**Comment by Connor1996** [comment]
1. Didn't test with the latest BlobDB.
2. No exact plan, but will
