### ISSUE TITLE
An issues about TitanTableBuilder::Add()

### ISSUE THREAD

**Issue by Borelset** [tikv/titan#232]
I am reading the source code of titan, and I found an issue.

In TitanTableBuilder::Add() (pasted in below), there are several "if" & "else" statements, and I want to talking about the assertion in that.
In the last "else", there is an assertion that expecting builder_unbuffered() returns true.
But we can assume such a scenario: 
1. There is a memtable to be flushed, and it includes several **big kvs (i.e., has big value)** and some **blob indexes (i.e., the type of their key is kTypeBlobIndex)** generated by GC. 
2. When flushing, a few big kvs are added to the TitanTableBuilder first with TitanTableBuilder::Add (the below function), which add them in a blob file, and because the number of them is few, the state of BlobfileBuilder is still Buffered.  
3. Then, add a blob index with TitanTableBuilder::Add(), and it will reach the last "else". In this case, because the state of BlobfileBuilder is Buffered, the assertion will fail.

I'm not sure whether my understanding is correct, and it looks like a potential problem.

```
/* titan/src/table_builder.cc */

void TitanTableBuilder::Add(const Slice& key, const Slice& value){

  if (ikey.type == kTypeBlobIndex &&
      cf_options_.blob_run_mode == TitanBlobRunMode::kFallback) {

      ....// processing something only when fallback

   }else if (ikey.type == kTypeValue &&
             cf_options_.blob_run_mode == TitanBlobRunMode::kNormal){

      ....// processing something when encountering kTypeValue keys

   }else if (ikey.type == kTypeBlobIndex && cf_options_.level_merge &&
             target_level_ >= merge_level_ &&
             cf_options_.blob_run_mode == TitanBlobRunMode::kNormal) {

      ....// processing something when running level merge in compaction

   } else { 
    // processing when encountering kTypeBlobIndex or kTypeMerge
    assert(builder_unbuffered()); 
    base_builder_->Add(key, value);
  }
}
```

**Comment by Connor1996** [comment]
Nice catch! You're correct. The code neglects the kTypeBlobIndex and KTypeMerge. Would you like to file a PR to fix it?

**Comment by Borelset** [comment]
@Connor1996 Sure. I have submitted a PR.
