### ISSUE TITLE
[BUG!] Reopen database will cause all blobfile gc score = 0

### ISSUE THREAD

**Issue by apple-ouyang** [tikv/titan#242]
I add a test in PR #241
After reopen the database, The livedata of blob will be 0, and the gc score of them will be 0.
Then all blob files will not be gc afterward!
We need a way to store the livedata.
For example in the MANIFEST file or some file in the disk.

**Comment by Connor1996** [comment]
Please check `InitializeGC` impl, it does get the livedata of blob and calculate the gc score at opening.

**Comment by apple-ouyang** [comment]
Sorry I make a mistake. The problem is about my test case.
