### ISSUE TITLE
how to use compression for titan?

### ISSUE THREAD

**Issue by hiqsociety** [tikv/titan#263]
how to use compression for titan? i saw the delta compression, is there a configuration setting to enable it?

**Comment by tabokie** [comment]
https://github.com/tikv/titan/blob/66a7a246e73ecc280963a4b7bbf3f0707deedf02/include/titan/options.h#L85

The compression type is defined here:
https://github.com/facebook/rocksdb/blob/79f08d7ffa6d34d9ca3357777bcb335884a56cfb/include/rocksdb/compression_type.h#L17

**Comment by hiqsociety** [comment]
how do i do this configuration in tidb?

**Comment by tabokie** [comment]
https://github.com/tikv/tikv/blob/47d8c9e483db762cefe8725abac9f5110e97ae63/etc/config-template.toml#L873

"Delta compression" is a feature request, compression in general is supported long ago.

**Comment by cscetbon** [comment]
@tabokie did someone look into that feature proposal though ?

**Comment by tabokie** [comment]
@cscetbon Unfortunately no. We don't have the bandwidth and this is a very low-priority feature in the scope of TiKV. (An intern implemented zstd dictionary compression years ago and we haven't gotten around to test it in TiKV...)
