### ISSUE TITLE
GC in level_merge

### ISSUE THREAD

**Issue by Peiqi0714** [tikv/titan#276]
I can't understand the GC method of level_merge:
1. if blobA's garbage meets threshold, add a gc tag to involve blobA in next merge
2. but only a part of keys in blobA is compaction related keys, how to gc the rest of the keys in next merge?
Thanks a lot！！

**Comment by Connor1996** [comment]
Just rewrite the still valid kv in a new blob file in next merge. So level_merge would increase write amplification.

**Comment by zyzboys** [comment]
> 

yes,i know.but I still have 2 questions
1.But if I don’t set a gc tag to this vtable, it still involve in a merge if it Has compaction related keys. 
2.only valid compaction related keys can be rewritten，if some keys never involves in a compaction，the vtable still contains valid values even though the portion is small，and we cant delete the vtable. how can we solve the problem，this may cause huge space amplification

**Comment by zyzboys** [comment]
> > 
> 
> yes,i know.but I still have 2 questions 1.But if I don’t set a gc tag to this vtable, it still involve in a merge if it Has compaction related keys. 2.only valid compaction related keys can be rewritten，if some keys never involves in a compaction，the vtable still contains valid values even though the portion is small，and we cant delete the vtable. how can we solve the problem，this may cause huge space amplification

vtable means blobfile here

**Comment by Connor1996** [comment]
1. Yes, check `ShouldMerge`
2. That's true. We have observed it in tests. It has huge space amplification for update intensive workload. That's why it's not GA.

**Comment by zyzboys** [comment]
> 1. Yes, check `ShouldMerge`
> 2. That's true. We have observed it in tests. It has huge space amplification for update intensive workload. That's why it's not GA.

thanks，but i noticed that when I open db, a regular gc Thread will be initialized (it will quit and never call again if no file needs go).even we enable level Merge, I found that when I
reopen a db，this regular gc thread will be initialized and clean some blob files which meet threshold. But if open a new db（level merge enable），this thread will be initialized and quit quickly，cant do regular gc in the future unless i reopen the db

**Comment by Connor1996** [comment]
Level merge is a alternative to regular gc, so need to call background gc if level merge enabled
