### ISSUE TITLE
parameter file_size is always 0

### ISSUE THREAD

**Issue by Peiqi0714** [tikv/titan#279]
https://github.com/tikv/titan/blob/master/src/blob_gc_job.cc
in function DoRunGC：
![image](https://github.com/tikv/titan/assets/58964909/c8a82f3d-8429-4da0-b4cc-1149eec63d21)
it seems file_size is always 0, it never get increased in this function, looks like a small bug

**Comment by Connor1996** [comment]
yes, same as https://github.com/tikv/titan/issues/236
