### ISSUE TITLE
Question about `TitanDBImpl::GetOldestSnapshotSequence()`

### ISSUE THREAD

**Issue by jonahgao** [tikv/titan#280]
I am currently unfamiliar with the codebase.

Is it safe to return `kMaxSequenceNumber` here if there are no snapshots, 
or should we return `db->GetLatestSequenceNumber()` instead?

https://github.com/tikv/titan/blob/e07da72e17f8638a9d4e81844bfbf380dad7e00f/src/db_impl.h#L247

**Comment by Connor1996** [comment]
Both are fine, it's used to get obsolete files. All files of which obsolete sequnce is smaller than oldest snapshot sequence are deleted. `kMaxSequenceNumber` and `db->GetLatestSequenceNumber()` take same effect here.

**Comment by jonahgao** [comment]
Got it. Thank you for patiently answering my question @Connor1996 🫡
