### ISSUE TITLE
bug: key in compaction filter is internal key instead of userkey after apply IsStackedBlobDbInternalCompactionFilter

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/titan#285]
since work with rocksdb_v6.29.5, (aka https://github.com/tikv/titan/pull/246), IsStackedBlobDbInternalCompactionFilter is implemented, which cause that the key passed to compaction filter from CompactionIterator::InvokeFilterIfNeeded is a internal key when value_type is kBlobIndex。 

place-1:
```
Slice& filter_key =
      (ikey_.type == kTypeValue ||
       !compaction_filter_->IsStackedBlobDbInternalCompactionFilter())
          ? ikey_.user_key
          : key_;
```

In TiKV, when we use compaction filter for GC, the obtained keys always have an extra portion:
Expected format:
```
MCE (userKey) + TSO
```
Actual format:
```
MCE (userKey) + TSO + (SeqNbr<<8 | ValueType::kBlobIndex)
```

**Comment by tabokie** [comment]
Good catch! cc @Connor1996 @tonyxuqqi

**Comment by Connor1996** [comment]
@guoxiangCN Would you like to file a PR to fix it? We can merge it now.

**Comment by guoxiangCN** [comment]
The solution I can currently think of is to call ParseInternalKey in Titan's compactionfilter and pass the userkey to the user's compactionfilter.
It may also be possible to handle it in RockSDB, but I am a bit troubled by the boundary between stackable blobdb, new blobdb, and titan, so I would like to take a look at the official developer's ideas

**Comment by Connor1996** [comment]
I think just let `IsStackedBlobDbInternalCompactionFilter` returns false for Titan

**Comment by guoxiangCN** [comment]
okay, it me do a test

**Comment by guoxiangCN** [comment]
@Connor1996 I have tried what you said, some unittest failed.
if IsStackedBlobDbInternalCompactionFilter returns false, the program will execute the logic of rocksdb integrated blobdb, which reads from the blob file, this will fail with a status of Status:: Corruption ("Unexpected blob index outside of action")

IsStackedBlobDbInternalCompactionFilter返回false时,无法区分程序的上下文是IntegratedBlobDB or Titan.

**Comment by Connor1996** [comment]
I see. I thought integrated blobdb doesn't have specific logic for that. Then let's use your original idea `call ParseInternalKey in Titan's compactionfilter and pass the userkey to the user's compactionfilter.`
