### ISSUE TITLE
Why titan forcibly set total_order_seek to true ?

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/titan#296]
https://github.com/tikv/titan/blob/master/src/db_impl.cc#L737C9-L737C9

titian forcibly set the total_order_seek to true, which disable the prefix_seek, Want to learn about the relevant background， thanks!

**Comment by Connor1996** [comment]
Seems not necessary. PTAL @DorianZheng

**Comment by guoxiangCN** [comment]
@DorianZheng Hello, could you please explain the original intention when you have time? We found that CPU consumption was particularly high when using Prefix seek, but we ultimately found that PrefixBloom was not used because Titan added the total_ Order_ Seek has been enabled. Can you please inform me of the reason for the design in the beginning, or what problems I encountered when doing so
If there is any offense, please bear with us

**Comment by Connor1996** [comment]
Theoretically, it wouldn't affect the titan correctness . How about changing it in your branch and see if there is any issue. If not, let's change it @guoxiangCN

**Comment by guoxiangCN** [comment]
Thank you for your suggestion. I will do what you said and give you a response after testing  @Connor1996
