### ISSUE TITLE
rate-limiter not limit the blobstorage read in compaction filter

### ISSUE THREAD

**Issue by mzygQAQ** [tikv/titan#324]
In compaction filter, for the entry that who's type = kTypeBlobIndex, a blob read will emit, this read not controlled by rate-limiter.

we set rocksdb.rate-bytes-per-sec="200M" and rate-mode="all-io", the compaction read reach 600M/s

**Comment by mzygQAQ** [comment]
@v01dstar

**Comment by mzygQAQ** [comment]
i made a mistake, the compact read not count the reads in compaction filter, so There are still issues in other stuff.
but theproblem in the title still exists

**Comment by Connor1996** [comment]
Nice catch. Indeed, All cases for compaction filter have this problem.

**Comment by mzygQAQ** [comment]
> i made a mistake, the compact read not count the reads in compaction filter, so There are still issues in other stuff. but theproblem in the title still exists

i made a mistak too, the compact read metrics in tikv actually count the blob read flow in titan compaction filter's read (blob_storage.get()).
because it's counted bya thread local IOSTATS_ADD(bytes_wriiten) in every Write function in WritableFileWriter  and Read function in RandomAccessFileReader/SequnceFileRead..., it doesn't need additional variable tracking and manual counting.

That can explain why even after adding rocksdb.rate-bytes-per-sec=200M/s&io type="all-io" to a tikv (which uses the apiV1TTL feature), Grafana's panel still shows its comparison read still exceeding 600M/s

**Comment by mzygQAQ** [comment]
@Connor1996  Hello, do you have any suggestions for repair?  The execution path of blob_storage.get() is a critical path, which accepts both front-end reads and reads from compactFilter. The simplest way I can think of is to simply execute RequestToken in the filter, which doesn't seem very native

**Comment by v01dstar** [comment]
We can propagate `rate_limiter_priority` all the way from compaction filter to `RandomAccessFileReader::Read`

**Comment by v01dstar** [comment]
> We can propagate `rate_limiter_priority` all the way from compaction filter to `RandomAccessFileReader::Read`

I was looking at newer versions of RocksDB. In the current version 6.29. We can propagate `bool for_compaction` through to `RandomAccessFileReader::Read`, seems this can fix the issue.
